workspace:
  base: /Xmap
  path: src/github.com/Veiasai/Xmap

pipeline:
  backend:
    image: maven:3.5.3-jdk-9
    volumes:
      - /home/administrator/mavenhub/:/root/.m2
    commands:
      - cd ./code/java-backend
      - mvn clean package
      - mv ./target/Xmap-1.0.0.jar ./target/Xmap.jar
    when:
        branch: [ master ]

  docker:
    image: plugins/docker
    repo: veiasai/server
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
        branch: [ master ]

  notify:
    image: drillster/drone-email
    secrets: [EMAIL_HOST, EMAIL_PORT, EMAIL_USERNAME, EMAIL_PASSWORD]
    from: 3395176096@qq.com
    recipients: [ 3395176096@qq.com ]

services: