version: '3'

networks:
  lan:

services:

  proxy:
    image: nginx
    container_name: neo4j-ha-proxy
    networks:
      - lan
    ports: 
      - "8081:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - master
      - slave1
      - slave2

  master:
    image: neo4j:3.1-enterprise
    container_name: core-placeholder
    ports: 
      - "8089:7474"
      - "8088:7687"
    volumes: 
      - ./data1:/data
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_ha_serverId=1
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_initialHosts=master:5001,slave1:5555,slave2:5001
    

# Use this to make sure master pushes TXs to both slaves, by default it will be only one
#      - NEO4J_ha_tx__push__factor=2

  slave1:
    image: neo4j:3.1-enterprise
    volumes: 
      - ./data2:/data
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_serverId=2
      - NEO4J_ha_initialHosts=master:5001,slave1:5555,slave2:5001
      - NEO4J_ha_host_coordination=slave1:5555
      - NEO4J_ha_host_data=slave1:6666
      - NEO4J_ha_slave__only=true
      - NEO4J_ha_pull__interval=5s # Default value is disabled but we want slave to poll master for test

  slave2:
    image: neo4j:3.1-enterprise
    container_name: read-placeholder
    volumes: 
      - ./data3:/data
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_serverId=3
      - NEO4J_ha_initialHosts=master:5001,slave1:5555,slave2:5001
      - NEO4J_ha_host_coordination=slave2:5001
      - NEO4J_ha_host_data=slave2:6001
      - NEO4J_ha_slave__only=true
      - NEO4J_ha_pull__interval=5s # Default value is disabled but we want slave to poll master for test