version: '3'

services:
  java:
    image: java:jre
    container_name: xmap-java
    ports:
      - "8080:8080"
    volumes:
      - ./xmap.jar:/xmap.jar
    command: java -jar /xmap.jar --spring.profiles.active=prodB
    environment: 
      - FLUENTD_HOST=132.232.35.84
      - FLUENTD_PORT=24224

  neo:
    image: neo4j:3.1-enterprise
    container_name: xmap-neo
    ports: 
      - "7474:7474"
      - "7687:7687"
    volumes: 
      - ./data:/data
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo

  

